# Log in

curl -X POST -H "Content-Type: application/json" -d '{"userId": 1}' {{baseUrl}}/login -c cookies.txt

### 

# Log out

curl -X POST {{baseUrl}}/logout -b cookies.txt

### 

# Create a user

curl -X POST -H "Content-Type: application/json" -d '{"firstName": "New", "lastName": "User", "birthDate": 946684800, "latitude": 40.5, "longitude": 75.0}' {{baseUrl}}/users

### 

# Get all users

curl {{baseUrl}}/users

### 

# Get users nearby a certain user (within a certain radius in meters)

curl '{{baseUrl}}/users/nearby?userId=1&radiusInMeters=400'

### 

# Get user by id

curl {{baseUrl}}/users/1

### 

# Add a profile picture to a user

curl -X POST -F "profilePicture=@/Users/brig/Downloads/temp.jpeg" {{baseUrl}}/profile-pictures -b cookies.txt

### 

# Update a user by id

curl -X PUT -H "Content-Type: application/json" -d '{"firstName": "Edited", "lastName": "User", "birthDate": 946684800, "bio": "I love coding", "hiddenOnMap": true, "interestedInFriends": true, "interestedInDating": true, "interestedInBusiness": true, "interestedInHelp": true, "latitude": 40.5, "longitude": 75.0}' {{baseUrl}}/users/1

### 

# Delete user by id

curl -X DELETE {{baseUrl}}/users/1