CREATE TABLE IF NOT EXISTS User (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  locationLastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);